"""empty message

Revision ID: c664ad4fe8fc
Revises: 7f15fee680d9
Create Date: 2023-07-19 18:52:46.581757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c664ad4fe8fc'
down_revision = '7f15fee680d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_share', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_pending', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('is_pending')
        batch_op.drop_column('price_per_share')

    # ### end Alembic commands ###
